### ISSUE TITLE
UI front-end sprint: Bugs, design, testing, & packaging

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#1135]
## Specify type:
- Enhancement
- UI

## Description
- [x] API calls & response structure updates #1177 
- [x] Bugs/issues #1164 #1165 #1184 #1186 
- [x] Build/packaging updates #1180 #1186 
- [x] Copy, Design & View updates, #1144 #1160 #1177 #1194 
  - Infinite scroll, `1144`
  - Copy `1194`
  - Credentials, `1160`
  - Unreachable hosts, `1177`
- [x] Testing updates, #1150 #1172
