### ISSUE TITLE
UI front-end sprint: Bugs, framework, and testing

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#1195]
## Specify type:
- Enhancement
- UI

## Description
- [x] Bugs/issues #1258 
- [x] Build/packaging/framework updates #1206 #1225 #1251 
- [x] Copy, Design & View updates #1225 #1226 #1251 #1258 
  - Brand updates `1226`
- [x] Internationalization research and base #1225 
  - Django login templates
  - Base research
- Testing updates (ongoing)

**Comment by cdcabrera** [comment]
@kholdaway went ahead and closed this down since it's last sprints work. Going ahead and setting up another all encompassing collection of work for this sprint

**Comment by kholdaway** [comment]
👍
