### ISSUE TITLE
Provide sonar cross-server merge functionality

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1244]
## Specify type:
- Enhancement

### Priority:
- High

## Description:
Customers may have multiple sonar installations but desire a single deployment report.  Currently, sonar will not accept data from another sonar server.  This enhancement aims to modify the sonar server to:
- Accept sonar details report JSON data from any sonar server
- Move important source information into JSON so database lookups are not required
- Record origin server (server guid) so meta-data bread crumb is still meaningful
- Merge and de-duplicate systems into a single deployment report
___

## Enhancements:

- [x] #1245 (Generate and persist a sonar GUID to uniquely identify a sonar server)
- [x] #1246 (Modify fact endpoint so important source information is in JSON and relax source validation)
- [x] #1247 (Create reports/merge API)
- [x] #1248 (Modify qpc report merge so it can take either report ids and job ids)
- [x] #1250 (UI: Migrate API endpoints to reports/merge)
- [x] #1249 (Remove jobs/merge API)

## Acceptance Criteria:
- [x] Verify that details reports from multiple servers can be uploaded, merged, and system deduplication performed.
