### ISSUE TITLE
[Design Document] - Collect and return all raw facts

### ISSUE THREAD

**Issue by bruno-fs** [quipucords/quipucords#2157]
## General Design

Each scanning module (`network`, `vcenter`, `sattelite`) will have a function `raw_facts_template`
which will return a dict mapping all raw fact names to `None`.

Example:

```python
def raw_facts_template():
    return {
        "some_fact": None,
        "another_fact: None,
    }
```
### places to initialize this function
- network: `quipucords.scanner.network/inspect_callback.py::_finalize_hosts`
- satellite: `quipucords/scanner/satellite/six.py::host_fields` and `quipucords/scanner/satellite/five.py::hosts_facts`
- vcenter: `quipucords/scanner/vcenter/inspect.py::InspectTaskRunner::parse_vm_props`

### how to test

Given the following "processing function" for each type of scan:
- network: `_process_network_fact` on `quipucords/fingerprinter/task.py`
- sattelite: `_process_sattelite_fact` on `quipucords/fingerprinter/task.py`
- vcenter: `_process_vcenter_fact` on `quipucords/fingerprinter/task.py`

Refactor and implement tests using the following guidelines:
- Refactor the data initialization for tests of fact processing functions 
  - Replace mocked initialization of facts like this `{}` with the appropriate `raw_facts_template()` (example [here](https://github.com/quipucords/quipucords/blob/d25996fc482793dd5e5bc715786e57a2865130a6/quipucords/fingerprinter/tests_fingerprint_task.py#L102))
- Add a new test submitting `raw_facts_template()` without addition of any data to the appropriate fact processing function (example [here](https://github.com/quipucords/quipucords/blob/d25996fc482793dd5e5bc715786e57a2865130a6/quipucords/fingerprinter/tests_fingerprint_task.py#L1056-L1085))

___

## Acceptance Criteria

- [x] rename network util `results_template` to `raw_facts_template` to match this design
- [x] rename test_all_facts_with_null_value -> test_process_network_scan_all_facts_with_null_value
- [x] implement this design for all types of scan:
  - [x] network
  - [x] sattelite
  - [x] vcenter

**Comment by bruno-fs** [comment]
delivered with 1.0.1 release
