### ISSUE TITLE
UI React front-end 

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#240]
# Opening a new issue
___

## Specify type:
- Enhancement

## Description:
React front-end
- [x] UI and build scripts,  PR #243 
- [x] Initial UI navigation layout, PR #251 
- [x] Base template and views, PR #274 #275 
- [x] Initial API hooks into mock, PR #282 
- [x] Base documentation for UI setup, PR #287
