### ISSUE TITLE
I want to obtain a RHEL deployment report from the inspection of multiple data sources.

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#334]
## Specify type:
- Enhancement

## Description:
After running a inspection of one or more data sources the data should be deduplicated and presented via the reporting endpoint.

### Fact Processing:
The fact endpoint should be updated to handle data passed from multiple data sources and provide back an identifier for report viewing.

The inspection flow should be updated to programmatically pass the data sources facts instead of via HTTP. 

### Deduplication:
Systems within a Network (Ansible) data source should be deduplicated via:
- Subscription Manager ID
- dmidecode bios uuid

Systems between Network and VCenter data sources should be deduplicated via:
- dmidecode bios uuid vs. vm uuid
- mac address

### RHEL Deployment Report:
Provide a report based on the list of systems from an inspection scan. Each system should provide:
- System ID
- Operating System
- CPU sockets
- VM Host (if applicable)
- VM Cluster (if applicable)

___

## Work items:

- [x]  https://github.com/quipucords/quipucords/issues/329
- [x] https://github.com/quipucords/quipucords/issues/335
- [x] https://github.com/quipucords/quipucords/issues/336
- [x] https://github.com/quipucords/quipucords/issues/337
- [x] https://github.com/quipucords/quipucords/issues/338
- [x] https://github.com/quipucords/quipucords/issues/339
- [x] https://github.com/quipucords/quipucords/issues/340

**Comment by chambridge** [comment]
All work items closed!
