### ISSUE TITLE
UI React front-end: API interaction, unit testing and view development

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#434]
## Specify type:
- Enhancement
- UI

## Description:
- [x] About dialog/modal, #450 
- [x] App updates ... bug fixes #513 
- [x] Basic unit test(s) related to Redux, #447 
- [x] Basic unit test(s) related to Sources view
  - evaluated components as Jest snapshots associated with sprint goals
- [x] Basic unit test(s) related to Scans view
  - evaluated components as Jest snapshots associated with sprint goals
- [x] Build updates; General, Mock API, SCSS, #462 #471 #508  ... bug fixes #466 
- [x] Component additions; Toast Notifications, #469 
- [x] Credentials components, and view implementation, #500 #513 #516 
- [x] Login page, initial Django templates and basic routes, #518 
- [ ] ReadMe install updates #535 
- [x] Redux API states for endpoints, #437 #447, #463 
- [x] Routing updates to reflect Django paths, #442
- [x] Scans components, and view implementation, #446 #470 #513 #516 
- [x] Sources components, and updates #521
