### ISSUE TITLE
UI front-end sprint: Testing, Form Integration, & View refinement

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords#534]
## Specify type:
- Enhancement
- UI

## Description:
- [x] Add Credentials modal/dialog, #596 #601 #603 #619 
- [x] API Redux updates, #619 #661 #677 
  - authorization headers
  - update/remove boilerplate
  - view and component optimizations
- [x] Build updates, #567 #685 #688 
  - Swagger
  - ~~Style linter~~ Postponed while considering SCSS integration into the Create React App setup through imports
- [x] Credentials view updates, #601 #603 #633 #661 #677 
- [x] Design updates, #563 #566 #653 
- Localization
  - Initial research
- [x] Paging implementation,  #677 
- [x] Patternfly React updates, #641 
- [x] Scans view updates, #633 #677
- [x] Sources view updates, #633 #677
- [x] Testing updates
  - Travis unit test review
  - Redux unit tests
- [x] Tooltips, #566
- [x] Toolbar optimize, #658  #677 
- [x] User authentication, #661 #687 
- [x] Wizard and form integrations, #581 #685 #689

**Comment by cdcabrera** [comment]
#689 closes this issue
